### ISSUE TITLE
Incorrect paths to assets

### ISSUE THREAD

**Issue by casatir** [MaitreRenard18/Terrario-2#11]
Hi guys!

Just to let you know that there is a typo on assets path for image load: `Images/PLayer/` should be `Images/Player/` without the capital `L`. The typo appears 4 times in `player.py` I guess.

This makes Terrario crash on startup on case-sensitive OS (like GNU/Linux).

Nice work!

**Comment by MaitreRenard18** [comment]
Thank you I fixed it, it was due to my stupid classmate who does not know how to type.

**Comment by cmoi-ugo** [comment]
> Thank you I fixed it, it was due to my stupid classmate who does not know how to type.

Its true, even the best can sometimes make mistakes.

**Comment by MaitreRenard18** [comment]
Except you are not part of the bests.

**Comment by cmoi-ugo** [comment]
> Except you are not part of the bests.

It's also true.
