### ISSUE TITLE
Pypi module is broken

### ISSUE THREAD

**Issue by casatir** [MaitreRenard18/Terrario-2#17]
After installing from Pypi with `pip3 install terrario` (which is nice :+1:), I get

```python
from Classes.game import Game
ModuleNotFoundError: No module named 'Classes'
```

This is due to 

- [x] relative module imports are not relatives
- [x] asset imports are neither relatives

I'll submit two PR, one for each issue in order to fix this.

**Comment by casatir** [comment]
Once #18 and #19 are merged, I guess there will remains a tiny issue in order to fix this.

In `Terrario.pyw`, import should be absolute since it's not a module but it seems you used it to produce `__main__.py` on Pypi where the import should be relative...

@MaitreRenard18 can you post (here or PM) the method you used to publish on Pypi? Your `setup.py` or `pyproject.toml` should be fine.

**Comment by MaitreRenard18** [comment]
Here is my ```setup.cfg```:
```
[metadata]
name = terrario
version = 0.0.11
author = MaitreRenard18, Wagister
author_email = maitre.renardowo@gmail.com
description = A 2D mining game made with Pygame.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/MaitreRenard18/Terrario-2
project_urls =
    Bug Tracker = https://github.com/MaitreRenard18/Terrario-2/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
install_requires =
    requests
    importlib-metadata; python_version < "3.8"
    pygame >= 2.1.1
    opensimplex
include_package_data = True

[options.packages.find]
where = src

[project.scripts]
terrario = "run"
```

and my ```pyproject.toml```:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pygame >= 2.1.1",
    "opensimplex"
]
build-backend = "setuptools.build_meta"
```

**Comment by MaitreRenard18** [comment]
By replacing
```py
 from Classes.game import Game
```
with
```py
from terrario.Classes.game import Game
```
I managed to fix the issue, I don't know if it's the optimal solution. But it works.

**Comment by casatir** [comment]
To me, the best practice should be to put all under a `src/terrario/` directory and to use only a `pyproject.toml` (no need to have a `setup.cfg`).

I can submit a PR to show you how, then feel free to go the way you want.
