### ISSUE TITLE
Path issues on case-sensitive OS

### ISSUE THREAD

**Issue by casatir** [MaitreRenard18/Terrario-2#22]
Some paths are not found on case sensitives OS. This prevent the game from starting.

Here are some examples:

 * `Images/UI/logo.png` and  `Images/UI/Logo.png`
 * `Saves/` and `saves/`
 * `Images/Thumbnails/World 1.png` and `images/thumbnails/World 1.png`

I can submit a PR to fix this if you want.

Let me point that it's more common to use lower case paths (without blank space) everywhere, specifically to avoid this kind of issue.

**Comment by cmoi-ugo** [comment]
I changed all the names of textures and folders in the code. There should be no more spaces or capital letters. The game should now work on case sensitive OS.

**Comment by casatir** [comment]
`Images` should be renamed `images`. Doing so, I can start the game and recover my saves. Congrats!

**Comment by casatir** [comment]
Here is a list of files/folders containing capital letter (but that does not seems to prevent the game from working):
 * Terrario.pyw
 * Props
 * images/Thumbnails
 * images/Thumbnails/world_1.png
 * Requirements.txt
 * Classes

**Comment by cmoi-ugo** [comment]
I renamed all the files/folders now they only contain lower letters. It should work better
