### ISSUE TITLE
Enlevez les majuscules des noms de dossiers (ou du moins mettez des path cohérents pour vos fichiers)

### ISSUE THREAD

**Issue by eyouga** [MaitreRenard18/Terrario-2#24]
Tout vos dossiers ont des majuscules dans leurs nom, sauf que a plusieurs reprises quand vous specifiez les path à certains fichiers dans votre code, vous les oubliez. Vous developpez sans doute sous Windows donc vous n'avez pas vu le problème car NTFS (le systeme de fichiers natif à Windows) ne discrime pas en fonction des majuscules (Fonts et fonts sont deux noms de dossiers identiques sous NTFS) mais la plupart des systemes de fichiers natifs à Linux (ext4, btrfs ect...) discriminent d'après les majuscules (Fonts et fonts sont deux dossiers differents). Donc quand on lance le programmme sous linux, pygame renvoie une erreur pour fichier non existant. Ma recommandation est d'enlever les majuscules des noms de fichiers comme ça vous êtes sur de ne plus les oublier.

**Comment by LTE-creator** [comment]
Duplicat #22, Mettez à jour sur pip car l'erreur pop encore

**Comment by eyouga** [comment]
Après verification, Fonts, Images, Props ont tous des maj, et images/thumbnails n'existe pas, après ca tout est clean de mon coté
